### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by bogzyeet** [hamzaharoon1314/SnapEnhanceModGen#8]
The build is failing everytime i try to run the workflow.... any fix? I wanna patch the new snapenhance v2 which was released today..

![image](https://github.com/hamzaharoon1314/SnapEnhance-LSPatch-Generator/assets/94661346/c71ecd1a-c896-4552-84ee-e792500c3d7a)

**Comment by Anashanif8091** [comment]
Please guide me how I patch new snapenhance to Snapchat

**Comment by hamzaharoon1314** [comment]
Sometimes it happens. You can try it after a day, and it'll run
