### ISSUE TITLE
Help me Snapenhace gentetor to Snapenhance 2.0.0 How To Patch?

### ISSUE THREAD

**Issue by Anashanif8091** [hamzaharoon1314/SnapEnhanceModGen#9]
Please Help Me I am using Old Version Snapenhance & I am third To Patch new version Snapenhance???

**Comment by hamzaharoon1314** [comment]
It's pre-patched, Follow Instructions for Pre-release.
1. First Install SnapFirst.apk and Login
2. Update with SnapLatest.apk and Then install SnapEnhance
